//! `Name` (RFC 5280 section 4.1.2.4): an `RDNSequence`, kept two ways --
//! the raw DER bytes (what path building compares an issuer field against a
//! candidate parent's subject field with, byte-for-byte: real certificate
//! chains are generated by tooling that encodes a CA's name identically
//! every time it appears, so this is both simpler and stricter than
//! attempting the full X.501 name-comparison algorithm) and a parsed list of
//! `(AttributeType, value)` pairs for a human-readable display string and,
//! as a fallback, a normalized comparison (Unicode case-folded, whitespace-
//! collapsed) for the rare case two encodings of an equal name differ only
//! in those cosmetic ways.

use alloc::string::String;
use alloc::vec::Vec;
use core::fmt::Write as _;

use crate::der::{DerError, Reader, tag};
use crate::error::X509Error;
use crate::oid::attr;

/// One `AttributeTypeAndValue`'s value: the DER tag it was encoded with (a
/// string type -- `PrintableString`, `UTF8String`, `IA5String`,
/// `TeletexString`, `BMPString` or `UniversalString`) plus its raw content
/// bytes. Crate-private: `Name`'s own public API (`raw`/`matches`/`display`)
/// never needs to hand one of these back to a caller.
#[derive(Clone, Copy, Debug)]
struct AttrValue<'a> {
    tag: u8,
    bytes: &'a [u8],
}

impl<'a> AttrValue<'a> {
    /// Best-effort decoding to a Rust `String`, for display and normalized
    /// comparison only (never used for byte-level equality). Invalid bytes
    /// are replaced rather than rejected: a cosmetic decode failure in an
    /// otherwise-valid certificate is not a reason to abort a handshake.
    fn to_display_string(self) -> String {
        match self.tag {
            tag::UTF8_STRING => String::from_utf8_lossy(self.bytes).into_owned(),
            tag::PRINTABLE_STRING | tag::IA5_STRING | tag::T61_STRING => {
                self.bytes.iter().map(|&b| char::from(b)).collect()
            }
            tag::BMP_STRING => decode_utf16be(self.bytes),
            tag::UNIVERSAL_STRING => decode_utf32be(self.bytes),
            _ => self.bytes.iter().map(|&b| char::from(b)).collect(),
        }
    }
}

fn decode_utf16be(bytes: &[u8]) -> String {
    let units: Vec<u16> = bytes.as_chunks::<2>().0.iter().map(|c| u16::from_be_bytes(*c)).collect();
    char::decode_utf16(units).map(|r| r.unwrap_or(char::REPLACEMENT_CHARACTER)).collect()
}

fn decode_utf32be(bytes: &[u8]) -> String {
    bytes
        .as_chunks::<4>()
        .0
        .iter()
        .map(|c| u32::from_be_bytes(*c))
        .map(|v| char::from_u32(v).unwrap_or(char::REPLACEMENT_CHARACTER))
        .collect()
}

/// One `RelativeDistinguishedName`: usually one `AttributeTypeAndValue`, but
/// a `SET` so, rarely, more than one. Crate-private, see [`AttrValue`].
#[derive(Clone, Debug)]
struct Rdn<'a> {
    attrs: Vec<(&'a [u8], AttrValue<'a>)>,
}

/// A parsed `Name`: the raw `RDNSequence` content bytes (for exact
/// comparison) plus its attributes (for display / normalized comparison).
#[derive(Clone, Debug)]
pub struct Name<'a> {
    raw: &'a [u8],
    rdns: Vec<Rdn<'a>>,
}

impl<'a> Name<'a> {
    /// Reads a `Name` (encoded, per the X.501 `CHOICE`, as its sole
    /// alternative `rdnSequence`, i.e. an ordinary `SEQUENCE`).
    pub fn parse(r: &mut Reader<'a>) -> Result<Name<'a>, X509Error> {
        let raw = r.expect_tag(tag::SEQUENCE)?;
        Name::from_rdn_sequence_content(raw)
    }

    /// Builds a `Name` directly from an already-extracted `RDNSequence`'s
    /// content bytes (the `SEQUENCE` tag and length already stripped).
    /// [`crate::path::TrustStore`] uses this to compare a trust anchor's
    /// owned, copied subject bytes against a certificate's parsed issuer
    /// [`Name`] without needing to keep the anchor's original certificate
    /// (and its borrowed lifetime) around.
    pub(crate) fn from_rdn_sequence_content(raw: &'a [u8]) -> Result<Name<'a>, X509Error> {
        let rdns = parse_rdns(raw)?;
        Ok(Name { raw, rdns })
    }

    /// The raw `RDNSequence` DER content bytes.
    pub fn raw(&self) -> &'a [u8] {
        self.raw
    }

    /// Whether `self` and `other` name the same entity: identical raw DER
    /// first (the common case for any chain generated by real CA tooling),
    /// falling back to a normalized comparison (attribute types equal in
    /// order, values equal after Unicode case-folding and whitespace
    /// collapse) that tolerates purely cosmetic re-encoding differences.
    pub fn matches(&self, other: &Name<'_>) -> bool {
        if self.raw == other.raw {
            return true;
        }
        if self.rdns.len() != other.rdns.len() {
            return false;
        }
        self.rdns.iter().zip(other.rdns.iter()).all(|(a, b)| rdn_matches(a, b))
    }

    /// A human-readable `attr=value, attr=value` display string (most
    /// significant RDN first, i.e. in encoded order), for UI/logging only.
    pub fn display(&self) -> String {
        let mut out = String::new();
        for (i, rdn) in self.rdns.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            for (j, (oid, value)) in rdn.attrs.iter().enumerate() {
                if j > 0 {
                    out.push('+');
                }
                out.push_str(attr_label(oid));
                out.push('=');
                out.push_str(&value.to_display_string());
            }
        }
        out
    }
}

fn attr_label(oid: &[u8]) -> &'static str {
    match oid {
        attr::COMMON_NAME => "CN",
        attr::COUNTRY_NAME => "C",
        attr::ORGANIZATION_NAME => "O",
        attr::ORGANIZATIONAL_UNIT_NAME => "OU",
        attr::STATE_OR_PROVINCE_NAME => "ST",
        attr::LOCALITY_NAME => "L",
        _ => "OID",
    }
}

fn normalize(s: &str) -> String {
    let mut out = String::new();
    let mut last_was_space = true; // trims leading whitespace for free
    for c in s.chars().flat_map(char::to_lowercase) {
        if c.is_whitespace() {
            if !last_was_space {
                out.push(' ');
            }
            last_was_space = true;
        } else {
            out.push(c);
            last_was_space = false;
        }
    }
    while out.ends_with(' ') {
        out.pop();
    }
    out
}

fn rdn_matches(a: &Rdn<'_>, b: &Rdn<'_>) -> bool {
    if a.attrs.len() != b.attrs.len() {
        return false;
    }
    a.attrs.iter().zip(b.attrs.iter()).all(|((oid_a, val_a), (oid_b, val_b))| {
        oid_a == oid_b && normalize(&val_a.to_display_string()) == normalize(&val_b.to_display_string())
    })
}

fn parse_rdns<'a>(content: &'a [u8]) -> Result<Vec<Rdn<'a>>, X509Error> {
    let mut r = Reader::new(content);
    let mut rdns = Vec::new();
    while !r.is_empty() {
        let mut set = r.read_set().map_err(X509Error::from)?;
        let mut attrs = Vec::new();
        while !set.is_empty() {
            let mut atv = set.read_sequence().map_err(X509Error::from)?;
            let oid = atv.read_oid().map_err(X509Error::from)?;
            let tlv = atv.read_tlv().map_err(X509Error::from)?;
            if !atv.is_empty() {
                return Err(X509Error::InvalidName);
            }
            attrs.push((oid, AttrValue { tag: tlv.tag, bytes: tlv.content }));
        }
        if attrs.is_empty() {
            return Err(X509Error::InvalidName);
        }
        rdns.push(Rdn { attrs });
    }
    Ok(rdns)
}

/// Decodes an OID's raw content bytes to its dotted-decimal string, for
/// display of attribute types this crate does not have a short label for.
/// Never used for comparison (see [`crate::oid`]'s module doc).
#[allow(dead_code)] // reserved for a future "unrecognized OID" display path
pub(crate) fn oid_to_dotted(oid: &[u8]) -> Result<String, DerError> {
    let mut out = String::new();
    let mut arcs = decode_base128_arcs(oid)?.into_iter();
    let first = arcs.next().ok_or(DerError::InvalidOid)?;
    let (arc1, arc2) = if first < 40 {
        (0u64, first)
    } else if first < 80 {
        (1, first - 40)
    } else {
        (2, first - 80)
    };
    write!(out, "{arc1}.{arc2}").ok();
    for arc in arcs {
        write!(out, ".{arc}").ok();
    }
    Ok(out)
}

fn decode_base128_arcs(oid: &[u8]) -> Result<Vec<u64>, DerError> {
    let mut arcs = Vec::new();
    let mut acc: u64 = 0;
    for &b in oid {
        acc = acc.checked_shl(7).ok_or(DerError::InvalidOid)?;
        acc |= u64::from(b & 0x7f);
        if b & 0x80 == 0 {
            arcs.push(acc);
            acc = 0;
        }
    }
    Ok(arcs)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn seq(content: &[u8]) -> Vec<u8> {
        let mut out = alloc::vec![0x30u8, content.len() as u8];
        out.extend_from_slice(content);
        out
    }

    /// One single-valued RDN: `SET { SEQUENCE { OID, PrintableString } }`.
    fn printable_atv(oid: &[u8], s: &str) -> Vec<u8> {
        let mut atv_content = alloc::vec![0x06u8, oid.len() as u8];
        atv_content.extend_from_slice(oid);
        atv_content.push(0x13);
        atv_content.push(s.len() as u8);
        atv_content.extend_from_slice(s.as_bytes());
        let atv_seq = seq(&atv_content);
        let mut set = alloc::vec![0x31u8, atv_seq.len() as u8];
        set.extend_from_slice(&atv_seq);
        set
    }

    #[test]
    fn parses_and_displays_a_simple_two_rdn_name() {
        let mut rdn_seq = printable_atv(attr::COUNTRY_NAME, "US");
        rdn_seq.extend(printable_atv(attr::COMMON_NAME, "Test Root"));
        let der = seq(&rdn_seq);
        let mut r = Reader::new(&der);
        let name = Name::parse(&mut r).unwrap();
        assert_eq!(name.display(), "C=US, CN=Test Root");
    }

    #[test]
    fn identical_raw_bytes_match() {
        let der = seq(&printable_atv(attr::COMMON_NAME, "Example"));
        let mut r1 = Reader::new(&der);
        let mut r2 = Reader::new(&der);
        let a = Name::parse(&mut r1).unwrap();
        let b = Name::parse(&mut r2).unwrap();
        assert!(a.matches(&b));
    }

    #[test]
    fn case_and_whitespace_differences_still_match() {
        let der_a = seq(&printable_atv(attr::COMMON_NAME, "Example  Root"));
        let der_b = seq(&printable_atv(attr::COMMON_NAME, "example root"));
        let mut ra = Reader::new(&der_a);
        let mut rb = Reader::new(&der_b);
        let a = Name::parse(&mut ra).unwrap();
        let b = Name::parse(&mut rb).unwrap();
        assert!(a.matches(&b));
    }

    #[test]
    fn different_values_do_not_match() {
        let der_a = seq(&printable_atv(attr::COMMON_NAME, "Example Root"));
        let der_b = seq(&printable_atv(attr::COMMON_NAME, "Other Root"));
        let mut ra = Reader::new(&der_a);
        let mut rb = Reader::new(&der_b);
        let a = Name::parse(&mut ra).unwrap();
        let b = Name::parse(&mut rb).unwrap();
        assert!(!a.matches(&b));
    }

    #[test]
    fn empty_rdn_sequence_is_accepted_structurally() {
        // An empty Name (zero RDNs) is unusual but structurally valid DER;
        // it simply never matches or displays as anything meaningful.
        let der = seq(&[]);
        let mut r = Reader::new(&der);
        let name = Name::parse(&mut r).unwrap();
        assert_eq!(name.display(), "");
    }

    #[test]
    fn rejects_empty_rdn_set() {
        let der = seq(&[0x31, 0x00]); // a SET with zero AttributeTypeAndValues
        let mut r = Reader::new(&der);
        assert_eq!(Name::parse(&mut r).err(), Some(X509Error::InvalidName));
    }

    #[test]
    fn oid_to_dotted_decodes_common_name() {
        assert_eq!(oid_to_dotted(attr::COMMON_NAME).unwrap(), "2.5.4.3");
    }
}
