//! The embedded trust anchors: a Mozilla-derived root bundle, as DER bytes
//! generated by `scripts/fetch-roots.py` from the curl project's
//! `cacert.pem` (<https://curl.se/ca/cacert.pem>, itself derived from
//! Mozilla's NSS root list, MPL-2.0 -- see `THIRD_PARTY_NOTICES.md`). The
//! generated file is committed (`generated.rs`), not fetched at build time:
//! this crate has no build script and no network access when it is built
//! into the kernel or userspace (DECISIONS.md D27).
//!
//! [`trust_store`] parses every embedded root once per call (this crate has
//! no dependencies, so no `lazy_static`/`once_cell` to cache it with -- see
//! `otter-crypto::p256`'s module doc for the same tradeoff, made the same
//! way); callers should call it once and reuse the resulting [`TrustStore`]
//! for the process's lifetime rather than per handshake.

mod generated;

use crate::path::TrustStore;

/// Every embedded root's raw DER bytes.
pub use generated::ROOTS;

/// Builds a [`TrustStore`] from the embedded Mozilla-derived root bundle.
pub fn trust_store() -> TrustStore {
    TrustStore::from_der_roots(ROOTS)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_bundle_is_non_empty() {
        assert!(!ROOTS.is_empty(), "scripts/fetch-roots.py has not been run");
    }

    #[test]
    fn every_embedded_root_parses_and_is_a_ca() {
        let store = trust_store();
        // A handful of roots across the bundle might legitimately be
        // unparseable-by-this-crate legacy shapes (see TrustStore::from_der_roots'
        // doc comment); the overwhelming majority must still load.
        assert!(
            store.len() * 10 >= ROOTS.len() * 9,
            "expected at least 90% of {} embedded roots to load, got {}",
            ROOTS.len(),
            store.len()
        );
    }
}
