#!/usr/bin/env python3
"""Captures real-world certificate chains for otter-x509's tests (brief M8-T4).

For each of the six public hosts the brief lists, opens a TCP connection and
performs a TLS handshake (via the standard-library `ssl` module, Python
3.13+'s `SSLSocket.get_unverified_chain()`) purely to capture the
certificate chain the server presents -- no HTTP request is ever sent, and
Python's own certificate verification is disabled for the connection (we
want exactly what the server sent, not Python's opinion of it; otter-x509's
own tests are what validate the chain, against its own embedded root store,
at the recorded capture time).

Writes, per host, one DER file per certificate in the chain (leaf first, as
served) plus one text line to `manifest.txt` recording the host, certificate
count and Unix capture time -- a compact format, not JSON, so the
integration test that reads it needs no JSON parser (DECISIONS.md D27,
matching scripts/gen-crypto-vectors.py's fixture format). Every file here is
committed: TLS certificate chains change over time (renewal, CA rotation),
so this is a point-in-time capture the tests validate *as of that time*, not
something to be re-fetched on every run.

Usage: scripts/capture-chains.py
"""
import os
import socket
import ssl
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "crates", "otter-x509", "tests", "fixtures", "chains")

HOSTS = [
    "example.com",
    "www.google.com",
    "github.com",
    "www.cloudflare.com",
    "letsencrypt.org",
    "api.anthropic.com",
]


def capture_chain(host, port=443, timeout=10):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    with socket.create_connection((host, port), timeout=timeout) as sock:
        with ctx.wrap_socket(sock, server_hostname=host) as tls:
            chain = tls.get_unverified_chain()
    if not chain:
        raise RuntimeError(f"{host}: server presented no certificate chain")
    return list(chain)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    manifest_lines = []
    failures = []
    for host in HOSTS:
        print(f"capture-chains: connecting to {host}:443")
        try:
            capture_time = int(time.time())
            chain = capture_chain(host)
        except OSError as e:
            failures.append((host, str(e)))
            print(f"capture-chains: {host}: FAILED ({e})")
            continue
        for i, der in enumerate(chain):
            path = os.path.join(OUT_DIR, f"{host}_{i}.der")
            with open(path, "wb") as f:
                f.write(der)
        manifest_lines.append(f"{host}|{len(chain)}|{capture_time}")
        print(f"capture-chains: {host}: {len(chain)} certificates at unix time {capture_time}")

    manifest_path = os.path.join(OUT_DIR, "manifest.txt")
    with open(manifest_path, "w", encoding="utf-8") as f:
        f.write("# host|cert_count|capture_unix_time\n")
        f.write("# Generated by scripts/capture-chains.py -- do not hand-edit.\n")
        for line in manifest_lines:
            f.write(line + "\n")
    print(f"capture-chains: wrote manifest for {len(manifest_lines)} host(s) -> {manifest_path}")

    if failures:
        print(f"capture-chains: {len(failures)} host(s) failed:", file=sys.stderr)
        for host, err in failures:
            print(f"  {host}: {err}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
