#!/usr/bin/env python3
"""Generates otter-x509's embedded trust anchors (brief M8-T4).

Downloads the curl project's `cacert.pem` (a Mozilla-derived CA bundle,
MPL-2.0, <https://curl.se/ca/cacert.pem>), verifies it against a SHA-256
pinned below (so a compromised mirror or an unexpected format change fails
loudly instead of silently embedding different roots), extracts every
`-----BEGIN CERTIFICATE-----` PEM block, base64-decodes it to DER, and
writes `crates/otter-x509/src/roots/generated.rs`: a single
`pub static ROOTS: &[&[u8]]` array literal, one entry per root, committed to
the repository (DECISIONS.md D27: no network access, no build script, when
this crate is built into the kernel or userspace). otter-x509's own
`TrustStore::from_der_roots` parses each entry at run time and is tolerant
of any individual root it cannot parse (see that function's doc comment);
this script does only a cheap DER-shape sanity check (a plausible SEQUENCE
tag/length) before embedding, not a full parse.

The downloaded PEM itself is cached under build/roots-download/ (gitignored,
like scripts/gen-crypto-vectors.py's Wycheproof cache) so re-runs are
offline unless the pinned hash actually changes.

Usage: scripts/fetch-roots.py
"""
import base64
import hashlib
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE_DIR = os.path.join(ROOT, "build", "roots-download")
OUT_PATH = os.path.join(ROOT, "crates", "otter-x509", "src", "roots", "generated.rs")

CACERT_URL = "https://curl.se/ca/cacert.pem"
CACERT_NAME = "cacert.pem"
# SHA-256 of the downloaded cacert.pem, pinned so a compromised mirror or an
# unannounced format change fails loudly instead of silently embedding
# different roots. Established by fetching directly from curl.se over TLS
# and recording the hash (the same trust-on-first-fetch method
# scripts/gen-crypto-vectors.py uses for Project Wycheproof's files).
EXPECTED_SHA256 = "f66dff1bdf8f96060b8177976f8b7d9254bc89bc4db933d769f7384d28480bc9"

PEM_BLOCK_RE = re.compile(
    r"-----BEGIN CERTIFICATE-----\r?\n(?P<body>.*?)-----END CERTIFICATE-----",
    re.DOTALL,
)


def sha256_of(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def fetch_cacert():
    os.makedirs(CACHE_DIR, exist_ok=True)
    dest = os.path.join(CACHE_DIR, CACERT_NAME)
    if os.path.exists(dest) and sha256_of(dest) == EXPECTED_SHA256:
        print(f"fetch-roots: using cached {CACERT_NAME}")
    else:
        print(f"fetch-roots: downloading {CACERT_URL}")
        with urllib.request.urlopen(CACERT_URL, timeout=60) as resp:
            data = resp.read()
        with open(dest, "wb") as f:
            f.write(data)
        actual = sha256_of(dest)
        if actual != EXPECTED_SHA256:
            raise SystemExit(
                f"fetch-roots: SHA-256 mismatch for {CACERT_NAME}\n"
                f"  expected {EXPECTED_SHA256}\n  actual   {actual}"
            )
    with open(dest, "r", encoding="utf-8") as f:
        return f.read()


def extract_der_certs(pem_text):
    ders = []
    skipped = 0
    for m in PEM_BLOCK_RE.finditer(pem_text):
        b64_body = "".join(m.group("body").split())
        try:
            der = base64.b64decode(b64_body, validate=True)
        except (base64.binascii.Error, ValueError):
            skipped += 1
            continue
        # Cheap DER sanity check: a SEQUENCE tag, plausible length, and
        # non-trivial size -- otter-x509's own strict parser does the real
        # work at run time (and tolerates a root it cannot parse).
        if len(der) < 64 or der[0] != 0x30:
            skipped += 1
            continue
        ders.append(der)
    return ders, skipped


def rust_byte_array_literal(der):
    hex_bytes = ", ".join(f"0x{b:02x}" for b in der)
    return f"&[{hex_bytes}]"


def write_generated_rs(ders, source_sha256):
    lines = []
    lines.append("//! Embedded trust anchors: generated by `scripts/fetch-roots.py` from the")
    lines.append("//! curl project's `cacert.pem` (Mozilla-derived CA bundle, MPL-2.0,")
    lines.append("//! <https://curl.se/ca/cacert.pem>, source SHA-256")
    lines.append(f"//! `{source_sha256}`). Do not hand-edit; re-run the script instead.")
    lines.append("//!")
    lines.append(f"//! {len(ders)} root certificates, as raw DER byte strings.")
    lines.append("")
    lines.append(f"/// Every embedded root's raw DER bytes ({len(ders)} certificates).")
    lines.append("pub static ROOTS: &[&[u8]] = &[")
    for der in ders:
        lines.append(f"    {rust_byte_array_literal(der)},")
    lines.append("];")
    lines.append("")
    text = "\n".join(lines)
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"fetch-roots: wrote {len(ders)} roots -> {OUT_PATH}")


def main():
    pem_text = fetch_cacert()
    ders, skipped = extract_der_certs(pem_text)
    if skipped:
        print(f"fetch-roots: skipped {skipped} PEM block(s) that failed the cheap DER sanity check")
    if len(ders) < 50:
        raise SystemExit(f"fetch-roots: only found {len(ders)} usable certificates, expected far more; aborting")
    write_generated_rs(ders, EXPECTED_SHA256)


if __name__ == "__main__":
    main()
