#!/usr/bin/env python3
"""Generates otter-crypto's host-verified test fixtures (brief M8-T1).

Two kinds of fixture, both written to crates/otter-crypto/tests/vectors/ as
compact, pipe-delimited text (not the original JSON, so the Rust test code
needs no JSON parser -- DECISIONS.md D22/D27: this crate stays dependency-free
even in its tests):

  - Project Wycheproof vectors, downloaded from the C2SP/wycheproof GitHub
    repository's `testvectors_v1/` directory (the actively-maintained schema;
    the older top-level `testvectors/` layout is gone from that repo). Every
    downloaded file is checked against a SHA-256 pinned below before it is
    used, and a local copy is cached under build/ (like scripts/fetch-fonts.sh
    does for fonts) so re-runs are offline unless a hash actually changes.
    ChaCha20-Poly1305's file has ten test groups; only the one using the
    standard 96-bit nonce / 256-bit key / 128-bit tag is converted, since the
    other nine exist to test *parameter-size* validation that a Rust API with
    fixed-size array types (`&[u8; 12]`, `&[u8; 32]`) rejects at compile time
    rather than at runtime.

  - hashlib cross-checks: SHA-256/384/512 of a seeded-random message at every
    length 0..=1100 bytes, generated directly from Python's own `hashlib`
    (stdlib, not a "crypto crate" in the DECISIONS.md D2 sense -- this is
    host-side test tooling, exactly like gen-gfx-fixtures.py using `zlib` to
    make PNG fixtures). This is what catches padding-boundary bugs: message
    *content* diversity does not matter for that, only hitting every length
    relative to the 64-byte (SHA-256) and 128-byte (SHA-384/512) block size.

Usage: scripts/gen-crypto-vectors.py
"""
import hashlib
import json
import os
import random
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VECTORS_DIR = os.path.join(ROOT, "crates", "otter-crypto", "tests", "vectors")
CACHE_DIR = os.path.join(ROOT, "build", "crypto-vector-downloads")

WYCHEPROOF_BASE_URL = "https://raw.githubusercontent.com/C2SP/wycheproof/main/testvectors_v1"

# SHA-256 of each raw downloaded JSON file, so a compromised mirror or a
# format change upstream fails loudly instead of silently feeding different
# test data into the fixtures below.
WYCHEPROOF_FILES = {
    "chacha20_poly1305_test.json": "fe61d25f90e1bde4461d00eafe61049e5f29bd999f36b766df9cda90906ad53d",
    "hmac_sha256_test.json": "2d201cfa61d1bf95e6f5d07d96634b4a348b31e8eaa277ad7c8d09677b7a743f",
    "hmac_sha384_test.json": "28b9776e979dd755d852ca471043ea6cedce8b15f7a28abdf6ea9efd982b43c0",
    "hmac_sha512_test.json": "b6c90477bdb4a6fc8ee3d1f7b2c0b69a8dfffab34718abaa6cabd71cc2ba1207",
    "hkdf_sha256_test.json": "bb2b462a38b251cb52a2aede706d6d4b62b26864f4e80c95497507ddb07c5f1e",
    "hkdf_sha384_test.json": "69ff6ea3657bb9c1b8cdffbbb4e7832353d08fd15c0d9997b03f7a6b180e3678",
    "hkdf_sha512_test.json": "bb9a21f4e86041caf5d7792b030349f8ff289087f195b2fbc0fc0afc39deca6f",
}

# Reproducible across runs/machines: the hashlib cross-check fixture is
# regenerated identically every time this script runs.
CROSS_CHECK_SEED = 0x0DDBA11
CROSS_CHECK_MAX_LEN = 1100


def sha256_of(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def fetch_wycheproof(name, expected_sha256):
    os.makedirs(CACHE_DIR, exist_ok=True)
    dest = os.path.join(CACHE_DIR, name)
    if os.path.exists(dest) and sha256_of(dest) == expected_sha256:
        print(f"gen-crypto-vectors: using cached {name}")
    else:
        url = f"{WYCHEPROOF_BASE_URL}/{name}"
        print(f"gen-crypto-vectors: downloading {url}")
        with urllib.request.urlopen(url, timeout=60) as resp:
            data = resp.read()
        with open(dest, "wb") as f:
            f.write(data)
        actual = sha256_of(dest)
        if actual != expected_sha256:
            raise SystemExit(
                f"gen-crypto-vectors: SHA-256 mismatch for {name}\n"
                f"  expected {expected_sha256}\n  actual   {actual}"
            )
    with open(dest, "r", encoding="utf-8") as f:
        return json.load(f)


def write_fixture(name, header, rows):
    os.makedirs(VECTORS_DIR, exist_ok=True)
    path = os.path.join(VECTORS_DIR, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# {header}\n")
        f.write("# Generated by scripts/gen-crypto-vectors.py -- do not hand-edit.\n")
        for row in rows:
            f.write("|".join(row) + "\n")
    print(f"gen-crypto-vectors: wrote {len(rows)} rows -> {path}")
    return len(rows)


# --------------------------------------------------------------------------
# HMAC (Wycheproof MacTest)
# --------------------------------------------------------------------------

def gen_hmac_fixture(hash_name, wycheproof_name):
    doc = fetch_wycheproof(wycheproof_name, WYCHEPROOF_FILES[wycheproof_name])
    rows = []
    for group in doc["testGroups"]:
        for t in group["tests"]:
            rows.append((str(t["tcId"]), t["result"], t["key"], t["msg"], t["tag"]))
    return write_fixture(f"hmac_{hash_name}_wycheproof.txt", f"tcid|result|key_hex|msg_hex|tag_hex ({hash_name})", rows)


# --------------------------------------------------------------------------
# HKDF (Wycheproof HkdfTest)
# --------------------------------------------------------------------------

def gen_hkdf_fixture(hash_name, wycheproof_name):
    doc = fetch_wycheproof(wycheproof_name, WYCHEPROOF_FILES[wycheproof_name])
    rows = []
    for group in doc["testGroups"]:
        for t in group["tests"]:
            rows.append(
                (str(t["tcId"]), t["result"], t["ikm"], t["salt"], t["info"], str(t["size"]), t.get("okm", ""))
            )
    return write_fixture(
        f"hkdf_{hash_name}_wycheproof.txt",
        f"tcid|result|ikm_hex|salt_hex|info_hex|size|okm_hex ({hash_name})",
        rows,
    )


# --------------------------------------------------------------------------
# ChaCha20-Poly1305 (Wycheproof AeadTest)
# --------------------------------------------------------------------------

def gen_chacha20_poly1305_fixture():
    doc = fetch_wycheproof("chacha20_poly1305_test.json", WYCHEPROOF_FILES["chacha20_poly1305_test.json"])
    rows = []
    skipped_groups = 0
    for group in doc["testGroups"]:
        if (group["ivSize"], group["keySize"], group["tagSize"]) != (96, 256, 128):
            # Tests a nonce/key/tag size our fixed-size Rust API (`&[u8; 12]`,
            # `&[u8; 32]`, 16-byte tag) rejects at compile time -- see module
            # docstring.
            skipped_groups += 1
            continue
        for t in group["tests"]:
            rows.append(
                (str(t["tcId"]), t["result"], t["key"], t["iv"], t["aad"], t["msg"], t["ct"], t["tag"])
            )
    print(f"gen-crypto-vectors: chacha20_poly1305: skipped {skipped_groups} non-standard-size test group(s)")
    return write_fixture(
        "chacha20_poly1305_wycheproof.txt",
        "tcid|result|key_hex|iv_hex|aad_hex|msg_hex|ct_hex|tag_hex",
        rows,
    )


# --------------------------------------------------------------------------
# SHA-256/384/512 cross-check against Python's hashlib
# --------------------------------------------------------------------------

def gen_sha2_cross_check_fixture():
    rng = random.Random(CROSS_CHECK_SEED)
    rows = []
    for length in range(0, CROSS_CHECK_MAX_LEN + 1):
        message = bytes(rng.randrange(256) for _ in range(length))
        rows.append(
            (
                str(length),
                message.hex(),
                hashlib.sha256(message).hexdigest(),
                hashlib.sha384(message).hexdigest(),
                hashlib.sha512(message).hexdigest(),
            )
        )
    return write_fixture(
        "sha2_cross.txt",
        "len|message_hex|sha256_hex|sha384_hex|sha512_hex -- hashlib cross-check, every length 0..=1100",
        rows,
    )


def main():
    counts = {}
    counts["sha2_cross"] = gen_sha2_cross_check_fixture()
    for hash_name, wycheproof_name in (
        ("sha256", "hmac_sha256_test.json"),
        ("sha384", "hmac_sha384_test.json"),
        ("sha512", "hmac_sha512_test.json"),
    ):
        counts[f"hmac_{hash_name}"] = gen_hmac_fixture(hash_name, wycheproof_name)
    for hash_name, wycheproof_name in (
        ("sha256", "hkdf_sha256_test.json"),
        ("sha384", "hkdf_sha384_test.json"),
        ("sha512", "hkdf_sha512_test.json"),
    ):
        counts[f"hkdf_{hash_name}"] = gen_hkdf_fixture(hash_name, wycheproof_name)
    counts["chacha20_poly1305"] = gen_chacha20_poly1305_fixture()

    total_wycheproof = sum(v for k, v in counts.items() if k != "sha2_cross")
    print(f"gen-crypto-vectors: {total_wycheproof} Wycheproof cases, {counts['sha2_cross']} hashlib cross-check rows")


if __name__ == "__main__":
    main()
